server:
  port: 8002

spring:
  application:
    name: dp-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.14.4:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: dp-system
        uri: lb://dp-system
        predicates:
        - Path=/**/**
      - id: dp-risk
        uri: lb://dp-risk
        predicates:
        - Path=/**/**


feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: debug

